// <auto-generated />
using System;
using GestorWorkflow.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestorWorkflow.Data.Migrations
{
    [DbContext(typeof(GestorWorkflowDbContext))]
    [Migration("20250627132656_UserUpdate")]
    partial class UserUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestorWorkflow.Data.Models.EstadoModelo", b =>
                {
                    b.Property<int>("EstadoModeloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado_modelo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoModeloId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ativo");

                    b.Property<string>("CorHexadecimal")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("cor_hexadecimal");

                    b.Property<int?>("CriadoPorUtilizadorId")
                        .HasColumnType("int")
                        .HasColumnName("criado_por_utilizador_id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<int>("TipoEstadoId")
                        .HasColumnType("int")
                        .HasColumnName("tipo_estado_id");

                    b.HasKey("EstadoModeloId");

                    b.HasIndex("CriadoPorUtilizadorId");

                    b.HasIndex("TipoEstadoId");

                    b.ToTable("EstadoModelo");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.Permissao", b =>
                {
                    b.Property<int>("PermissaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_permissao");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissaoId"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<int>("TransicaoModeloId")
                        .HasColumnType("int")
                        .HasColumnName("id_transicao_modelo");

                    b.HasKey("PermissaoId");

                    b.HasIndex("TransicaoModeloId");

                    b.ToTable("Permissao");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.PosCondicao", b =>
                {
                    b.Property<int>("PosCondicaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_poscondicao");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PosCondicaoId"));

                    b.Property<string>("AcaoSql")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("acao_sql");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ativo");

                    b.Property<int?>("CriadoPorUtilizadorId")
                        .HasColumnType("int")
                        .HasColumnName("criado_por_utilizador_id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("PosCondicaoId");

                    b.HasIndex("CriadoPorUtilizadorId");

                    b.ToTable("PosCondicao");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.PreCondicao", b =>
                {
                    b.Property<int>("PreCondicaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_precondicao");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PreCondicaoId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ativo");

                    b.Property<string>("CondicaoSql")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("condicao_sql");

                    b.Property<int?>("CriadoPorUtilizadorId")
                        .HasColumnType("int")
                        .HasColumnName("criado_por_utilizador_id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("PreCondicaoId");

                    b.HasIndex("CriadoPorUtilizadorId");

                    b.ToTable("PreCondicao");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_status");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("StatusId");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Nome = "Ativo"
                        },
                        new
                        {
                            StatusId = 2,
                            Nome = "Pausado"
                        },
                        new
                        {
                            StatusId = 3,
                            Nome = "Concluído"
                        },
                        new
                        {
                            StatusId = 4,
                            Nome = "Cancelado"
                        },
                        new
                        {
                            StatusId = 5,
                            Nome = "Pendente"
                        });
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.TipoEstado", b =>
                {
                    b.Property<int>("TipoEstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_estado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoEstadoId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("TipoEstadoId");

                    b.ToTable("TiposEstado");

                    b.HasData(
                        new
                        {
                            TipoEstadoId = 1,
                            Nome = "Inicial"
                        },
                        new
                        {
                            TipoEstadoId = 2,
                            Nome = "Intermediário"
                        },
                        new
                        {
                            TipoEstadoId = 3,
                            Nome = "Final"
                        },
                        new
                        {
                            TipoEstadoId = 4,
                            Nome = "Decisão"
                        },
                        new
                        {
                            TipoEstadoId = 5,
                            Nome = "Aprovação"
                        });
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.TransicaoInstancia", b =>
                {
                    b.Property<int>("TransicaoInstanciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_transicao_instancia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransicaoInstanciaId"));

                    b.Property<DateTime>("DataExecucao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_execucao");

                    b.Property<string>("ErroMensagem")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("erro_mensagem");

                    b.Property<int?>("ExecutadoPorUtilizadorId")
                        .HasColumnType("int")
                        .HasColumnName("executado_por_utilizador_id");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("bit")
                        .HasColumnName("sucesso");

                    b.Property<int>("TransicaoModeloId")
                        .HasColumnType("int")
                        .HasColumnName("id_transicao_modelo");

                    b.Property<int>("WorkflowInstanciaId")
                        .HasColumnType("int")
                        .HasColumnName("id_workflow_instancia");

                    b.HasKey("TransicaoInstanciaId");

                    b.HasIndex("ExecutadoPorUtilizadorId");

                    b.HasIndex("TransicaoModeloId");

                    b.HasIndex("WorkflowInstanciaId");

                    b.ToTable("TransicaoInstancia");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.TransicaoModelo", b =>
                {
                    b.Property<int>("TransicaoModeloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_transicao_modelo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransicaoModeloId"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descricao");

                    b.Property<int>("EstadoDestinoId")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_destino");

                    b.Property<int?>("EstadoOrigemId")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_origem");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<int?>("PosCondicaoId")
                        .HasColumnType("int")
                        .HasColumnName("id_pos_condicao");

                    b.Property<int?>("PreCondicaoId")
                        .HasColumnType("int")
                        .HasColumnName("id_pre_condicao");

                    b.Property<int>("WorkflowModeloId")
                        .HasColumnType("int")
                        .HasColumnName("id_workflow_modelo");

                    b.HasKey("TransicaoModeloId");

                    b.HasIndex("EstadoDestinoId");

                    b.HasIndex("EstadoOrigemId");

                    b.HasIndex("PosCondicaoId");

                    b.HasIndex("PreCondicaoId");

                    b.HasIndex("WorkflowModeloId");

                    b.ToTable("TransicaoModelo");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.Utilizador", b =>
                {
                    b.Property<int>("UtilizadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_utilizador");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtilizadorId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Email");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Funcao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nome");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("PasswordHash");

                    b.HasKey("UtilizadorId");

                    b.ToTable("Utilizador");

                    b.HasData(
                        new
                        {
                            UtilizadorId = 1,
                            Email = "",
                            Funcao = "Admin",
                            Nome = "Administrador",
                            PasswordHash = ""
                        },
                        new
                        {
                            UtilizadorId = 2,
                            Email = "",
                            Funcao = "User",
                            Nome = "Utilizador Teste",
                            PasswordHash = ""
                        });
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.UtilizadorPermissao", b =>
                {
                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int")
                        .HasColumnName("id_Utilizador");

                    b.Property<int>("PermissaoId")
                        .HasColumnType("int")
                        .HasColumnName("id_Permissao");

                    b.HasKey("UtilizadorId", "PermissaoId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("Utilizador_Permissao");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.WorkflowInstancia", b =>
                {
                    b.Property<int>("WorkflowInstanciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_workflow_instancia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkflowInstanciaId"));

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_inicio");

                    b.Property<int?>("EstadoAtualId")
                        .HasColumnType("int")
                        .HasColumnName("estado_atual_id");

                    b.Property<int?>("IniciadoPorUtilizadorId")
                        .HasColumnType("int")
                        .HasColumnName("iniciado_por_utilizador_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<int>("WorkflowModeloId")
                        .HasColumnType("int")
                        .HasColumnName("id_workflow_modelo");

                    b.HasKey("WorkflowInstanciaId");

                    b.HasIndex("EstadoAtualId");

                    b.HasIndex("IniciadoPorUtilizadorId");

                    b.HasIndex("StatusId");

                    b.HasIndex("WorkflowModeloId");

                    b.ToTable("WorkflowInstancia");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.WorkflowModelo", b =>
                {
                    b.Property<int>("WorkflowModeloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_workflow_modelo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkflowModeloId"));

                    b.Property<int?>("AlteradoPorUtilizadorId")
                        .HasColumnType("int")
                        .HasColumnName("alterado_por_utilizador_id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ativo");

                    b.Property<int>("CriadoPorUtilizadorId")
                        .HasColumnType("int")
                        .HasColumnName("criado_por_utilizador_id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_ultima_alteracao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descricao");

                    b.Property<int>("EstadoInicialId")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_modelo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Versao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("versao");

                    b.HasKey("WorkflowModeloId");

                    b.HasIndex("AlteradoPorUtilizadorId");

                    b.HasIndex("CriadoPorUtilizadorId");

                    b.HasIndex("EstadoInicialId");

                    b.ToTable("WorkflowModelo");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.EstadoModelo", b =>
                {
                    b.HasOne("GestorWorkflow.Data.Models.Utilizador", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorUtilizadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestorWorkflow.Data.Models.TipoEstado", "TipoEstado")
                        .WithMany("EstadosModelo")
                        .HasForeignKey("TipoEstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CriadoPor");

                    b.Navigation("TipoEstado");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.Permissao", b =>
                {
                    b.HasOne("GestorWorkflow.Data.Models.TransicaoModelo", "TransicaoModelo")
                        .WithMany("Permissoes")
                        .HasForeignKey("TransicaoModeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransicaoModelo");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.PosCondicao", b =>
                {
                    b.HasOne("GestorWorkflow.Data.Models.Utilizador", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorUtilizadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CriadoPor");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.PreCondicao", b =>
                {
                    b.HasOne("GestorWorkflow.Data.Models.Utilizador", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorUtilizadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CriadoPor");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.TransicaoInstancia", b =>
                {
                    b.HasOne("GestorWorkflow.Data.Models.Utilizador", "ExecutadoPor")
                        .WithMany("TransicoesExecutadas")
                        .HasForeignKey("ExecutadoPorUtilizadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestorWorkflow.Data.Models.TransicaoModelo", "TransicaoModelo")
                        .WithMany("TransicoesInstancia")
                        .HasForeignKey("TransicaoModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorWorkflow.Data.Models.WorkflowInstancia", "WorkflowInstancia")
                        .WithMany("TransicoesInstancia")
                        .HasForeignKey("WorkflowInstanciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutadoPor");

                    b.Navigation("TransicaoModelo");

                    b.Navigation("WorkflowInstancia");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.TransicaoModelo", b =>
                {
                    b.HasOne("GestorWorkflow.Data.Models.EstadoModelo", "EstadoDestino")
                        .WithMany("TransicoesModeloDestino")
                        .HasForeignKey("EstadoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorWorkflow.Data.Models.EstadoModelo", "EstadoOrigem")
                        .WithMany("TransicoesModeloOrigem")
                        .HasForeignKey("EstadoOrigemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestorWorkflow.Data.Models.PosCondicao", "PosCondicao")
                        .WithMany("TransicoesModelo")
                        .HasForeignKey("PosCondicaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestorWorkflow.Data.Models.PreCondicao", "PreCondicao")
                        .WithMany("TransicoesModelo")
                        .HasForeignKey("PreCondicaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestorWorkflow.Data.Models.WorkflowModelo", "WorkflowModelo")
                        .WithMany("TransicoesModelo")
                        .HasForeignKey("WorkflowModeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoDestino");

                    b.Navigation("EstadoOrigem");

                    b.Navigation("PosCondicao");

                    b.Navigation("PreCondicao");

                    b.Navigation("WorkflowModelo");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.UtilizadorPermissao", b =>
                {
                    b.HasOne("GestorWorkflow.Data.Models.Permissao", "Permissao")
                        .WithMany("UtilizadorPermissoes")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorWorkflow.Data.Models.Utilizador", "Utilizador")
                        .WithMany("UtilizadorPermissoes")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissao");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.WorkflowInstancia", b =>
                {
                    b.HasOne("GestorWorkflow.Data.Models.EstadoModelo", "EstadoAtual")
                        .WithMany("WorkflowInstanciasAtivas")
                        .HasForeignKey("EstadoAtualId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestorWorkflow.Data.Models.Utilizador", "IniciadoPor")
                        .WithMany()
                        .HasForeignKey("IniciadoPorUtilizadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestorWorkflow.Data.Models.Status", "Status")
                        .WithMany("WorkflowInstancias")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorWorkflow.Data.Models.WorkflowModelo", "WorkflowModelo")
                        .WithMany("WorkflowInstancias")
                        .HasForeignKey("WorkflowModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoAtual");

                    b.Navigation("IniciadoPor");

                    b.Navigation("Status");

                    b.Navigation("WorkflowModelo");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.WorkflowModelo", b =>
                {
                    b.HasOne("GestorWorkflow.Data.Models.Utilizador", "AlteradoPor")
                        .WithMany()
                        .HasForeignKey("AlteradoPorUtilizadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestorWorkflow.Data.Models.Utilizador", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorUtilizadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorWorkflow.Data.Models.EstadoModelo", "EstadoInicial")
                        .WithMany("WorkflowModelos")
                        .HasForeignKey("EstadoInicialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlteradoPor");

                    b.Navigation("CriadoPor");

                    b.Navigation("EstadoInicial");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.EstadoModelo", b =>
                {
                    b.Navigation("TransicoesModeloDestino");

                    b.Navigation("TransicoesModeloOrigem");

                    b.Navigation("WorkflowInstanciasAtivas");

                    b.Navigation("WorkflowModelos");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.Permissao", b =>
                {
                    b.Navigation("UtilizadorPermissoes");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.PosCondicao", b =>
                {
                    b.Navigation("TransicoesModelo");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.PreCondicao", b =>
                {
                    b.Navigation("TransicoesModelo");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.Status", b =>
                {
                    b.Navigation("WorkflowInstancias");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.TipoEstado", b =>
                {
                    b.Navigation("EstadosModelo");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.TransicaoModelo", b =>
                {
                    b.Navigation("Permissoes");

                    b.Navigation("TransicoesInstancia");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.Utilizador", b =>
                {
                    b.Navigation("TransicoesExecutadas");

                    b.Navigation("UtilizadorPermissoes");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.WorkflowInstancia", b =>
                {
                    b.Navigation("TransicoesInstancia");
                });

            modelBuilder.Entity("GestorWorkflow.Data.Models.WorkflowModelo", b =>
                {
                    b.Navigation("TransicoesModelo");

                    b.Navigation("WorkflowInstancias");
                });
#pragma warning restore 612, 618
        }
    }
}
